#eureka:
#  instance:
#    prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url :
#        defaultZone: http://localhost:8761/eureka
#




spring:
    config:
      import:
        optional: CONFIG-SERVER
    profiles:
      active: prod

management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      RatingAndHotelCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
   instances:
    RatingHotelService:
     max-attempts: 3
     wait-duration: 5s

  rateLimiter:
    instance:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s


#retry:
#  instance:
#   RatingHotelService:
#    max-attempts: 3
#    wait-duration: 5s




